# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40dc237fd3979abe82271be933558d1efe0ebaa8f4aa1221f5b757d10af70ed7cc22cae4fc1fa61d049c16f07c4334b4c4bb4f91bb7ac0b09e1157cdbae501f8

test:
  secret_key_base: eba36d770459499c2e16ff2bc8195f0d042f76c247abc7ca4fd06b3a4a5b6f792ad34168e36d319d7f8a5e99f16df8eefcd76ea495a926909a1d1461aac0b79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
